# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Meta data
title: 'Dries Standaert - Designer'
author: 'Dries Standaert'
description: 'I design user interfaces and digital identities. Feel free to get in touch.'

# Site navigation
navigation:
  - title: Work
    url: work/
  - title: contact
    url: contact/
  - title: Matexi
    url: matexi/
  - title: Ferret
    url: ferret/
  - title: Werchter
    url: werchter/
  - title: Atlas Copco
    url: atlascopco/
  - title: Bene
    url: bene/
  - title: Oktav
    url: oktav/
  - title: maunga
    url: maunga/


# Jekyll settings
permalink: pretty

# Exclude these files from the build process
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
